# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'euskoEvents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for euskoEvents
pod 'Eureka', '~> 4.0'
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON', '~> 4.0'

end
